import type { Metadata } from "next";
import "./globals.css";

import {Assistant} from 'next/font/google'

const AssistantFont = Assistant({
  weight:['400','500','600','800'],
  subsets:['latin'],
  display:'swap'

})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${AssistantFont.className}antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
